name: pyMBIR_UI
channels:
  - conda-forge
dependencies:
  # base
  - python=3.12
  - versioningit
  - toml
  # GUI
  - qt
  - qtpy
  - pyqt
  # image
  - pillow
  - scikit-image
  - inflect
  - astropy
  - numpy
  - dxchange
  - h5py
  - tomopy
  - matplotlib
  # -- Development
  # utils
  - pre-commit
  # packaging
  - anaconda-client
  - boa
  - conda-build < 4
  - conda-verify
  - python-build
  # doc
  - pydocstyle
  - sphinx
  - sphinx_rtd_theme
  # pip
  - pip:
    - check-wheel-contents
    - pytest-playwright
    - pyqtgraph
    - NeuNorm
    - mpl_toolkits
