name: tomoORNL_ui
channels:
  - conda-forge
dependencies:
  - python
  - qt
  - pillow
  - scikit-image
  - inflect
  - qtpy
  - pyqt
  - astropy
  - numpy
  - dxchange
  - h5py
  - tomopy
  - matplotlib
  # -- Development
  # utils
  - pre-commit
  # packaging
  - anaconda-client
  - boa
  - conda-build < 4
  - conda-verify
  - python-build
  # doc
  - pydocstyle
  - sphinx
  - sphinx_rtd_theme
  # pip
  - pip:
    - NeuNorm
    - olefile
    - pyqtgraph
    - six
    - mpl_toolkits
    - check-wheel-contents
    - pytest-playwright
