name: pyMBIR_UI
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - qt
  - pillow
  - scikit-image
  - inflect
  - qtpy
  - pyqt
  - astropy
  - numpy
  - dxchange
  - h5py
  - tomopy
  - pip:
      - NeuNorm
      - olefile
      - pyqtgraph
      - six
      
