#!/usr/bin/env python

# from .NGI_GUI_indev import main
from src.angel.angel import main

import multiprocessing
import sys

__file__ = "Angel"

# Run the GUI
multiprocessing.freeze_support()

sys.exit(main(sys.argv))
